#pragma kernel CSMain

#include "UnityCG.cginc"

struct GPUObject
{
    int type;
    int materialIndex;
    float3 center;
    float radius;
    float3 v0;
    float3 v1;
    float3 v2;
    float3 min, max;
    float4x4 matWorld;
    float4x4 invMatWorld;
    float4x4 invTranspMatWorld;
};

struct GPUMaterial
{
    float3 color;
    float ambient;
    float diffuse;
    float specular;
};

struct GPULight
{
    float3 position;
    float3 color;
};

StructuredBuffer<GPUObject> objects;
StructuredBuffer<GPUMaterial> materials;
StructuredBuffer<GPULight> lights;

RWTexture2D<float4> Result;

cbuffer CameraBuffer
{
    float3 camPos;
    float3 camForward;
    float3 camRight;
    float3 camUp;
    float fov;
    int width;
    int height;
};

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)width || id.y >= (uint)height) return;

    float u = (id.x + 0.5f)/width * 2 - 1;
    float v = (id.y + 0.5f)/height * 2 - 1;

    float aspect = (float)width / (float)height;
    float3 rayDir = normalize(camForward + u * aspect * camRight * tan(fov*0.5) + v * camUp * tan(fov*0.5));
    float3 rayOrigin = camPos;

    float3 finalColor = float3(0,0,0);

    float tMin = 1e20;
    int hitIndex = -1;
    float3 hitNormal;

    // Intersecao de raio e objeto
    for (int i = 0; i < (int)objects.Length; i++)
    {
        GPUObject obj = objects[i];

        if (obj.type == 0) // Esfera
        {
            float3 L = rayOrigin - obj.center;
            float a = dot(rayDir, rayDir);
            float b = 2*dot(rayDir, L);
            float c = dot(L,L) - obj.radius*obj.radius;
            float disc = b*b - 4*a*c;
            if (disc < 0) continue;

            float t0 = (-b - sqrt(disc)) / (2*a);
            float t1 = (-b + sqrt(disc)) / (2*a);
            float t = (t0>0)? t0 : ((t1>0)? t1 : -1);
            if (t>0 && t<tMin)
            {
                tMin = t;
                hitIndex = i;
                float3 p = rayOrigin + t*rayDir;
                hitNormal = normalize(p - obj.center);
            }
        }
        else if (obj.type == 1) // Trianglo
        {
            float3 e1 = obj.v1 - obj.v0;
            float3 e2 = obj.v2 - obj.v0;
            float3 pvec = cross(rayDir, e2);
            float det = dot(e1, pvec);
            if (abs(det) < 1e-6) continue;
            float invDet = 1.0/det;
            float3 tvec = rayOrigin - obj.v0;
            float uu = dot(tvec, pvec)*invDet;
            if (uu < 0 || uu > 1) continue;
            float3 qvec = cross(tvec, e1);
            float vv = dot(rayDir, qvec)*invDet;
            if (vv < 0 || uu+vv >1) continue;
            float t = dot(e2, qvec)*invDet;
            if (t>0 && t<tMin)
            {
                tMin = t;
                hitIndex = i;
                hitNormal = normalize(cross(e1,e2));
            }
        }
        else if (obj.type == 2) // Cubo
        {
            const float EPS = 1e-5;

            // Transformar para posicao global
            float3 O = mul(obj.invMatWorld, float4(rayOrigin, 1)).xyz;
            float3 D = normalize(mul(obj.invMatWorld, float4(rayDir, 0)).xyz);

            float3 boxMin = obj.min;
            float3 boxMax = obj.max;

            float3 t0 = (boxMin - O) / D;
            float3 t1 = (boxMax - O) / D;

            float3 tmin3 = min(t0, t1);
            float3 tmax3 = max(t0, t1);

            float tNear = max(max(tmin3.x, tmin3.y), tmin3.z);
            float tFar  = min(min(tmax3.x, tmax3.y), tmax3.z);

            if (tNear < tFar && tFar > 0)
            {
                float tHit = (tNear > 0) ? tNear : tFar;

                if (tHit < tMin)
                {
                    float3 localPoint = O + tHit * D;
                    float3 n;

                    // Determina a normal com base em qual tmin/tmax foi usado
                    if (tHit == t0.x) n = float3(-1,0,0);
                    else if (tHit == t1.x) n = float3(1,0,0);
                    else if (tHit == t0.y) n = float3(0,-1,0);
                    else if (tHit == t1.y) n = float3(0,1,0);
                    else if (tHit == t0.z) n = float3(0,0,-1);
                    else n = float3(0,0,1);

                    // Converte ponto local para espaço mundo para definir tMin corretamente
                    float3 worldPoint = mul(obj.matWorld, float4(localPoint,1)).xyz;

                    hitIndex = i;
                    tMin = length(worldPoint - rayOrigin);

                    hitNormal = normalize(mul(obj.invTranspMatWorld, float4(n,0)).xyz);
                }
            }
        }

    }

    if (hitIndex >= 0)
    {
        GPUObject hitObj = objects[hitIndex];
        GPUMaterial mat = materials[hitObj.materialIndex];
        float3 hitPoint = rayOrigin + tMin*rayDir;

        finalColor = mat.color * mat.ambient;

        for (int li = 0; li < (int)lights.Length; li++)
        {
            GPULight light = lights[li];
            float3 L = normalize(light.position - hitPoint);
            float lightDist = length(light.position - hitPoint);

            // Shadow check
            bool inShadow = false;
            for (int si = 0; si < (int)objects.Length; si++)
            {
                if (si == hitIndex) continue;
                GPUObject obj = objects[si];

                const float EPS = 1e-6;

                if (obj.type == 0) // Esfera
                {
                    float3 O = hitPoint + hitNormal*0.001;
                    float3 D = L;
                    float3 C = obj.center;
                    float r = obj.radius;
                    float3 Ls = O - C;
                    float a = dot(D,D);
                    float b = 2*dot(D,Ls);
                    float c = dot(Ls,Ls)-r*r;
                    float disc = b*b-4*a*c;
                    if (disc>0)
                    {
                        float t0 = (-b - sqrt(disc))/(2*a);
                        float t1 = (-b + sqrt(disc))/(2*a);
                        float t = (t0>0)?t0:((t1>0)?t1:-1);
                        if (t>0 && t < lightDist) { inShadow=true; break; }
                    }
                }
                else if (obj.type == 1) // Trianglo
                {
                    float3 O = hitPoint + hitNormal*0.001;
                    float3 D = L;

                    float3 e1 = obj.v1 - obj.v0;
                    float3 e2 = obj.v2 - obj.v0;
                    float3 pvec = cross(D, e2);
                    float det = dot(e1, pvec);
                    if (abs(det) < 1e-6) continue;
                    float invDet = 1.0/det;
                    float3 tvec = O - obj.v0;
                    float su = dot(tvec, pvec)*invDet;
                    if (su < 0 || su > 1) continue;
                    float3 qvec = cross(tvec, e1);
                    float sv = dot(D, qvec)*invDet;
                    if (sv < 0 || su+sv >1) continue;
                    float t = dot(e2, qvec)*invDet;
                    if (t>0 && t < lightDist) { inShadow=true; break; }
                }
                else if (obj.type == 2) // Cubo
                {
                    float3 O = hitPoint + hitNormal * 0.001;   // origem do raio de sombra (world)
                    float3 D = L;                              // direção do raio de sombra (world)

                    // Transformar para espaço local do box
                    float3 localO = mul(obj.invMatWorld, float4(O,1)).xyz;
                    float3 localD = normalize(mul(obj.invMatWorld, float4(D,0)).xyz);

                    float tnear = -1e20;
                    float tfar  =  1e20;

                    for(int axis = 0; axis < 3; axis++)
                    {
                        float o = localO[axis];
                        float d = localD[axis];
                        float minB = obj.min[axis];
                        float maxB = obj.max[axis];

                        if (abs(d) < 1e-6)
                        {
                            if (o < minB || o > maxB)
                            {
                                tnear = 1e20;
                                break;
                            }
                        }
                        else
                        {
                            float t1 = (minB - o) / d;
                            float t2 = (maxB - o) / d;
                            if (t1 > t2) { float tmp = t1; t1 = t2; t2 = tmp; }

                            tnear = max(tnear, t1);
                            tfar  = min(tfar, t2);

                            if (tnear > tfar || tfar < 0) { tnear = 1e20; break; }
                        }
                    }

                    if (tnear < 1e20)
                    {
                        float tLocal = (tnear > 0) ? tnear : tfar;
                        if (tLocal <= 0) continue;

                        // Converter interseção local para mundo
                        float3 localHit = localO + tLocal * localD;
                        float3 worldHit = mul(obj.matWorld, float4(localHit,1)).xyz;

                        // Distancia real no espaço mundo
                        float tWorld = length(worldHit - O);

                        if (tWorld > 1e-4 && tWorld < lightDist)
                        {
                            inShadow = true;
                            break;
                        }
                    }
                }

            }

            if (!inShadow)
            {
                float NdotL = max(0,dot(hitNormal,L));
                finalColor += mat.color * mat.diffuse * NdotL * light.color;
            }
        }

        finalColor /= lights.Length;
    }

    Result[id.xy] = float4(finalColor,1);
}